import React, { useState, useEffect } from 'react'
import { marketAPI } from '../../utils/api.js'
import { FileText, RefreshCw, AlertTriangle, CheckCircle } from 'lucide-react'

export default function UserReport() {
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  const load = async () => {
    setLoading(true); setError(null)
    try { const r = await marketAPI.getReport(); setData(r.data) }
    catch (e) { setError(e.response?.data?.detail || 'Failed to load report') }
    finally { setLoading(false) }
  }

  useEffect(() => { load() }, [])

  return (
    <div>
      <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:24 }}>
        <div>
          <h1 style={{ fontSize:24, fontWeight:800, color:'var(--text)' }}>AI Diagnostic Report</h1>
          <p style={{ color:'var(--text-muted)', fontSize:14, marginTop:2 }}>Module 9 · 10 · Explainable AI Narrative + Reporting</p>
        </div>
        <button onClick={load} disabled={loading} style={{ display:'flex', alignItems:'center', gap:8, padding:'9px 16px', background:'var(--primary)', color:'#fff', border:'none', borderRadius:'var(--radius-sm)', fontSize:13, fontWeight:600, cursor:'pointer' }}>
          <RefreshCw size={14} style={{ animation:loading?'spin 1s linear infinite':'none' }}/> Regenerate
        </button>
      </div>

      {loading && (
        <div style={{ textAlign:'center', padding:80, color:'var(--text-muted)' }}>
          <FileText size={36} color="var(--primary)" style={{ marginBottom:12 }}/>
          <div>Generating AI diagnostic report…</div>
          <div style={{ fontSize:12, marginTop:4 }}>This may take a few seconds</div>
        </div>
      )}

      {error && (
        <div style={{ background:'#fef2f2', border:'1px solid #fecaca', borderRadius:'var(--radius)', padding:20, color:'#dc2626' }}>
          <div style={{ display:'flex', gap:10, alignItems:'center' }}>
            <AlertTriangle size={18}/><div>{error}</div>
          </div>
        </div>
      )}

      {data && (
        <div style={{ display:'flex', flexDirection:'column', gap:20 }}>
          {/* Header card */}
          <div style={{ background:'linear-gradient(135deg, var(--violet-600) 0%, var(--violet-800) 100%)', borderRadius:'var(--radius)', padding:28, color:'#fff' }}>
            <div style={{ fontSize:11, opacity:0.65, letterSpacing:'0.1em', marginBottom:6 }}>MARKET DIAGNOSTIC REPORT · {data.date}</div>
            <div style={{ fontSize:20, fontWeight:800, marginBottom:4 }}>Daily Structural Intelligence Report</div>
            <div style={{ fontSize:13, opacity:0.8 }}>Generated by {data.generated_by} · Market Diagnosis Platform</div>
            {data.regime_summary && (
              <div style={{ marginTop:16, background:'rgba(255,255,255,0.12)', borderRadius:8, padding:'10px 14px', fontSize:14, border:'1px solid rgba(255,255,255,0.2)' }}>
                📊 {data.regime_summary}
              </div>
            )}
          </div>

          {/* Narrative */}
          <div style={{ background:'#fff', borderRadius:'var(--radius)', border:'1px solid var(--border)', boxShadow:'var(--shadow)', padding:28 }}>
            <h3 style={{ fontSize:14, fontWeight:700, color:'var(--primary)', letterSpacing:'0.06em', marginBottom:16 }}>📄 STRUCTURAL ANALYSIS NARRATIVE</h3>
            <div style={{ fontSize:14, lineHeight:1.8, color:'var(--text)', whiteSpace:'pre-wrap' }}>{data.narrative}</div>
          </div>

          {/* Key findings */}
          {data.key_findings?.length > 0 && (
            <div style={{ background:'#fff', borderRadius:'var(--radius)', border:'1px solid var(--border)', boxShadow:'var(--shadow)', padding:28 }}>
              <h3 style={{ fontSize:14, fontWeight:700, color:'var(--primary)', letterSpacing:'0.06em', marginBottom:16 }}>🔍 KEY FINDINGS</h3>
              <div style={{ display:'flex', flexDirection:'column', gap:10 }}>
                {data.key_findings.map((f, i) => (
                  <div key={i} style={{ display:'flex', alignItems:'flex-start', gap:12, padding:'12px 14px', background:'var(--violet-50)', borderRadius:10, border:'1px solid var(--border)' }}>
                    <CheckCircle size={16} color="var(--primary)" style={{ flexShrink:0, marginTop:1 }}/>
                    <span style={{ fontSize:14, color:'var(--text)' }}>{f}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Risk flags */}
          {data.risk_flags?.length > 0 && (
            <div style={{ background:'#fff', borderRadius:'var(--radius)', border:'1px solid #fecaca', boxShadow:'var(--shadow)', padding:28 }}>
              <h3 style={{ fontSize:14, fontWeight:700, color:'#dc2626', letterSpacing:'0.06em', marginBottom:16 }}>🚨 RISK FLAGS</h3>
              <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
                {data.risk_flags.map((f, i) => (
                  <div key={i} style={{ padding:'10px 14px', background:'#fef2f2', borderRadius:8, fontSize:13, color:'#991b1b', border:'1px solid #fecaca' }}>{f}</div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
